title = "echo::rust(ğŸ¦€)"

[[posts]]
id = "073773ae-e0d7-4210-ae70-08809a667cd8"
title = "FÃ¸rste innlegg! ğŸ“"
description = "echo har endelig fÃ¥tt en interessegruppe for Rust! ğŸ¦€"
date = "Thu, 01 May 2025 18:00:00 GMT"
content = """
Hei alle sammen! ğŸ‘‹

echo har nÃ¥ fÃ¥tt en egen interessegruppe for alle som liker og er nysgjerrige pÃ¥
programmeringssprÃ¥ket Rust ğŸ¦€ğŸ’»! Du trenger absolutt ikke Ã¥ ha noe erfaring for
med Rust Ã¥ bli med, vi er Ã¥pen for alle, uansett nivÃ¥! ğŸŒ±.

Vi planlegger Ã¥ arrangere spennende aktiviteter bÃ¥de for nybegynnere og for dere
som allerede har litt kjennskap til Rust. MÃ¥let er Ã¥ utforske sprÃ¥ket sammen og
bli enda bedre kjent med hvorfor vi liker det sÃ¥ godt ğŸ¤“âœ¨

Vi gleder oss til et lÃ¦rerikt og spennende kommende semester! ğŸš€ğŸ“š
"""
